version: "3"
services:
  petclinic:
    image: prasantk/spring-petclinic:${TAG}
    # ports:
    #   - 8080
    depends_on:
      - mysql
    environment:
      - VIRTUAL_HOST=${URL}
      - VIRTUAL_PORT=8080
  mysql:
    image: mysql
    # ports:
    # - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    # volumes:
    #   - "./conf.d:/etc/mysql/conf.d:ro"
networks:
  default:
    external:
      name: jenkins_default